#!/usr/bin/env bash

#@go get -u golang.org/x/tools/cmd/goimports

if ! command -v goimports &> /dev/null
then
  echo "goimports does not exist"
  exit
fi

echo ">>> goimports <<<"

FILES=$(goimports -l `./scripts/gols -d`)
if [ -n "${FILES}" ]; then
  echo "Error in files: "
  echo "${FILES}"
  echo '>>> Display changes: goimports -d -e `./scripts/gols -d`'
  echo '>>> Fix files      : goimports -w `./scripts/gols -d`'
  exit 1
fi
